### ISSUE TITLE
Merge everything into master and get rid of the other branches

### ISSUE THREAD

**Issue by jobovy** [jobovy/streamgap-aa#1]
The repository is currently a bit of a mess. I think we should just go to using master ASAP and delete all of the other branches (because they will be incorporated into master).

**Comment by jls713** [comment]
I have merged everything into master. I haven't deleted the other branches in case I have done something wrong!

**Comment by jobovy** [comment]
Okay, thanks! We can delete them once we've submitted the paper.

**Comment by jobovy** [comment]
Deleted other branches now that the paper is in press.
