### ISSUE TITLE
Clean up and document galpy implementation and mention in the paper

### ISSUE THREAD

**Issue by jobovy** [jobovy/streamgap-aa#2]
I still need to do some work going through the code, testing it, and writing some documentation.

Should also mention in the paper that we use galpy, that the various ways of calculating the kicks are implemented in galpy, and that the perturbed model is implemented in galpy.

**Comment by jls713** [comment]
I have now mentioned galpy.

**Comment by jobovy** [comment]
Thanks! Still cleaning up the code...
