### ISSUE TITLE
Write some documentation on what is in the py directory

### ISSUE THREAD

**Issue by jobovy** [jobovy/streamgap-aa#3]
I think we should make the repository public when we submit the paper and as such it would be good to just have a little bit of documentation on what the various notebooks are in the `py/` directory. I think the main ones are:
- [x] [StreamGapExample.ipynb](https://github.com/jobovy/streamgap-aa/blob/paper_jo/py/StreamGapExample.ipynb)
- [x] [GapsAngleFreqJz!=0.ipynb](https://github.com/jobovy/streamgap-aa/blob/paper_jo/py/GapsAngleFreqJz!%3D0.ipynb)
- [x] [galpyModelnonzeroJz.ipynb](https://github.com/jobovy/streamgap-aa/blob/paper_jo/py/galpyModelnonzeroJz.ipynb)

(do these make all of the plots in the paper?) with important stuff in
- [x] [custom_stripping_df.py](https://github.com/jobovy/streamgap-aa/blob/paper_jo/py/custom_stripping_df.py)

**Comment by jls713** [comment]
The first two plots in the paper are generated in StreamGapExample.ipynb

**Comment by jobovy** [comment]
Okay, I've added it to the list above. I don't think the plots in the notebook are the same as those in the paper though?

**Comment by jls713** [comment]
No. I think the most up-to-date plots are on my laptop but I haven't pushed them yet.

**Comment by jobovy** [comment]
Thanks for adding this. I added a note (in ea1db373d60ef83d89d937e6eeaec9dc4cd0f305) about the simulation data not being included, which means that the notebooks cannot actually be executed.
